### ISSUE TITLE
請問，日後是否能新增聖遺物總面板的調整呢?

### ISSUE THREAD

**Issue by ngarox** [Kurarion/Genshin-Calc#1]
作者您好:
從Enka.API 導入的資料，確實在第一手時很方便。
但更新資料有3min冷卻時間。
如果要在遊戲內頻繁更換已有的聖遺物，求出最大期望值。
能直接從總面板動手，會更為方便。

如蒙惠告，不勝感激。

**Comment by Kurarion** [comment]
@ngarox 
十分高興該工具能幫到您！

目前有考慮過通過聖遺物縂詞條限制，
自動求取特定傷害的理論最高期望及相應屬性分配情況。
但考慮到特定聖遺物獲取的隨機性以及個人原因並沒有持續開發下去（在dev分支已經擱置幾周了）。

十分抱歉，短時間可能是不會追加的。

**Comment by ngarox** [comment]
好的，辛苦作者了。 :>
