### ISSUE TITLE
您好 菲谢尔二命貌似有误

### ISSUE THREAD

**Issue by teslagao** [Kurarion/Genshin-Calc#2]
不应当加成奥兹攻击伤害

**Comment by Kurarion** [comment]
缓存问题已完成修复，之后的更新无需强制刷新，应用会自动得到更新推送。

> 已经修复于 [7c7f7cb](https://github.com/Kurarion/Genshin-Calc/commit/7c7f7cb17561b777c6b4b0b4a062348505b33110)，目前已知因缓存问题可能导致更新无法反映。 十分抱歉，请暂时使用`Ctrl+F5`强制刷新解决。

**Comment by teslagao** [comment]
好使了 辛苦了大神
