### ISSUE TITLE
切换不同圣遗物预设时全队增益勾选会失效

### ISSUE THREAD

**Issue by shenxinyu1999** [Kurarion/Genshin-Calc#3]
作者您好！
如题，我想要对比多套深林套时切换发现即使切换后全队增益选项被勾选，但增益会消失。不清楚其他有全队增益的圣遗物有没有类似情况。

**Comment by Kurarion** [comment]
@shenxinyu1999 
试了一下，确实是会失效，其它类似的全队增益的圣遗物效果切换时也会有同样的问题。
感谢反馈！会尽快修复。
